# Generated by Django 5.2.4 on 2025-07-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VerifyOTPService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("AUTHENTICATE", "Authenticate"),
                            ("RESET_PASSWORD", "Reset Password"),
                            ("VERIFY", "Verify"),
                        ],
                        default="AUTHENTICATE",
                        max_length=17,
                    ),
                ),
                ("to", models.CharField(max_length=355)),
                ("code", models.CharField(max_length=5)),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "send_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("result", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("expire_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sms_service_verify_otp",
            },
        ),
    ]
